### ISSUE TITLE
z-wave

### ISSUE THREAD

**Issue by brianjking** [brianjking/hass-config#1]
````yaml
automation:
  - alias: Turn on office lights when there is movement
    trigger:
      - platform: state
        entity_id: sensor.motion_sensor
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: group.office_lights 

  - alias: Turn off lights when there is no motion
    trigger:
      - platform: state
        entity_id: sensor.motion_sensor
        state: 'off'
        for:
          minutes: 10
    action:
      service: homeassistant.turn_off
      entity_id: group.office_lights
````
