### ISSUE TITLE
Uber 

### ISSUE THREAD

**Issue by brianjking** [brianjking/hass-config#11]
https://home-assistant.io/components/sensor.uber/

````yaml
sensor 5:
  - platform: uber
    server_token: !secret uber_token
    start_latitude: !secret latitude 
    start_longitude: !secret longitude
`````
