### ISSUE TITLE
Motion Sensor Turn Off Automation

### ISSUE THREAD

**Issue by brianjking** [brianjking/hass-config#17]
````yaml
- alias: Turn on office lights when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_2_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.officebot

- alias: Turn off lights when there is no motion
  trigger:
    platform: state
    entity_id: sensor.motion_sensor
    state: 'off'
    for:
    minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: light.officebot
````
