### ISSUE TITLE
Enable debugging for Fluxer & LIFX to attempt to diagnose why LIFX Color 1000 bulb turns green

### ISSUE THREAD

**Issue by brianjking** [brianjking/hass-config#35]
- Debugging enabled in 62864f2d026e336b86bc37c326412d3ce77fd364.
- See [this issue](https://github.com/home-assistant/home-assistant/issues/6090) for more info

**Comment by brianjking** [comment]
After midnight fluxer seems to decide that it wants to turn `light.officebot` to green for an unknown reason.

````yaml
switch:
  platform: flux
  lights:
    - light.officebot
    - light.officebotfloor
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:59'
  start_colortemp: 3200
  sunset_colortemp: 2600
  stop_colortemp: 2500
  disable_brightness_adjust: True 
  mode: mired
````
